<?php
namespace AmirKateb\AiCoreClient;
use AmirKateb\AiCoreClient\Http\Transport;
use AmirKateb\AiCoreClient\Value\SseEvent;
final class Client
{
    private Transport $http;
    public function __construct(string $baseUrl,string $apiKey,int $timeoutSeconds=300,int $connectTimeoutSeconds=10){$root=rtrim($baseUrl,'/');if(!str_ends_with($root,'/api/v1'))$root.='/api/v1';$this->http=new Transport($root,$apiKey,$timeoutSeconds,$connectTimeoutSeconds);}
    public function withHeaders(array $headers):self{$clone=clone $this;$clone->http=$this->http->withHeaders($headers);return$clone;}public function withClientRequestId(string $id):self{return$this->withHeaders(['X-Client-Request-ID'=>$id]);}public function withOrigin(string $origin):self{return$this->withHeaders(['Origin'=>$origin]);}public function batchBuilder():BatchBuilder{return new BatchBuilder($this);}
    public function status():array{return$this->get('/status');}public function health():array{return$this->get('/health');}public function usage(string $range='30d'):array{return$this->get('/usage',['range'=>$range]);}public function limits():array{return$this->get('/limits');}public function models(?string $capability=null):array{return$this->get('/models',array_filter(['capability'=>$capability]));}public function capabilities():array{return$this->get('/capabilities');}
    public function chat(array $payload,?string $idempotencyKey=null):RequestHandle{return$this->submit('/chat',$payload,$idempotencyKey);}public function chatStream(array $payload,?string $idempotencyKey=null):RequestHandle{return$this->submit('/chat/stream',$payload,$idempotencyKey);}public function text(array $payload,?string $idempotencyKey=null):RequestHandle{return$this->submit('/text',$payload,$idempotencyKey);}public function imageGeneration(array $payload,?string $key=null):RequestHandle{return$this->submit('/images/generations',$payload,$key);}public function speech(array $payload,?string $key=null):RequestHandle{return$this->submit('/audio/speech',$payload,$key);}public function embeddings(array $payload,?string $key=null):RequestHandle{return$this->submit('/embeddings',$payload,$key);}public function moderation(array $payload,?string $key=null):RequestHandle{return$this->submit('/moderations',$payload,$key);}public function rerank(array $payload,?string $key=null):RequestHandle{return$this->submit('/rerank',$payload,$key);}public function videoGeneration(array $payload,?string $key=null):RequestHandle{return$this->submit('/videos/generations',$payload,$key);}public function createResponse(array $payload,?string $key=null):RequestHandle{return$this->submit('/responses',$payload,$key);}
    public function imageEdit(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/images/edits','image',$file,$payload,$key);}public function visionAnalyze(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/vision/analyze','image',$file,$payload,$key);}public function ocr(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/ocr','image',$file,$payload,$key);}public function audioAnalyze(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/audio/analyze','audio',$file,$payload,$key);}public function transcription(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/audio/transcriptions','audio',$file,$payload,$key);}public function audioTranslation(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/audio/translations','audio',$file,$payload,$key);}public function documentAnalyze(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/documents/analyze','document',$file,$payload,$key);}public function videoAnalyze(string $file,array $payload,?string $key=null):RequestHandle{return$this->submitFile('/video/analyze','video',$file,$payload,$key);}
    public function requests(array $query=[]):array{return$this->get('/requests',$query);}public function request(string $id):array{return$this->get('/requests/'.rawurlencode($id));}public function cancelRequest(string $id):array{return$this->post('/requests/'.rawurlencode($id).'/cancel',[]);}public function retryRequest(string $id):RequestHandle{$data=$this->post('/requests/'.rawurlencode($id).'/retry',[]);return new RequestHandle($this,(string)$data['request_id'],$data);}public function streamRequest(string $id,callable $listener,int $after=0):void{$this->http->sse('/requests/'.rawurlencode($id).'/stream',$listener,$after);}public function downloadMedia(string $id,string $target):string{return$this->http->download('/requests/'.rawurlencode($id).'/media',$target);}
    public function batches(array $query=[]):array{return$this->get('/batches',$query);}public function createBatch(array $items,array $metadata=[],?string $idempotencyKey=null):BatchHandle{$data=$this->post('/batches',['items'=>$items,'metadata'=>$metadata],$idempotencyKey);return new BatchHandle($this,(string)$data['batch_id'],$data);}public function batch(string $id):array{return$this->get('/batches/'.rawurlencode($id));}public function cancelBatch(string $id):array{return$this->post('/batches/'.rawurlencode($id).'/cancel',[]);}
    public function waitForRequest(string $id,int $timeoutSeconds=300,float $pollSeconds=1.0):array{$deadline=microtime(true)+$timeoutSeconds;do{$row=$this->request($id);if(in_array($row['status']??null,['success','failed','cancelled'],true))return$row;usleep((int)(max(.1,$pollSeconds)*1_000_000));}while(microtime(true)<$deadline);throw new \RuntimeException('Timed out while waiting for request '.$id);}
    public function waitForBatch(string $id,int $timeoutSeconds=600,float $pollSeconds=1.5):array{$deadline=microtime(true)+$timeoutSeconds;do{$row=$this->batch($id);if(in_array($row['status']??null,['completed','completed_with_errors','cancelled'],true))return$row;usleep((int)(max(.1,$pollSeconds)*1_000_000));}while(microtime(true)<$deadline);throw new \RuntimeException('Timed out while waiting for batch '.$id);}
    public static function idempotencyKey(string $prefix='req'):string{return$prefix.'_'.bin2hex(random_bytes(16));}
    private function submit(string $path,array $payload,?string $key):RequestHandle{$data=$this->post($path,$payload,$key);return new RequestHandle($this,(string)$data['request_id'],$data);}private function submitFile(string $path,string $field,string $file,array $payload,?string $key):RequestHandle{$headers=$key?['Idempotency-Key'=>$key]:[];$multipart=$payload;$multipart[$field]=['file'=>$file];$data=$this->http->json('POST',$path,['multipart'=>$multipart,'headers'=>$headers]);return new RequestHandle($this,(string)$data['request_id'],$data);}private function get(string $path,array $query=[]):array{return$this->http->json('GET',$path,['query'=>$query]);}private function post(string $path,array $payload,?string $key=null):array{$headers=$key?['Idempotency-Key'=>$key]:[];return$this->http->json('POST',$path,['json'=>$payload,'headers'=>$headers]);}
}
